# A hardened Dependabot configuration file for both version and security updates.
# For all configuration options, see the official documentation:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Harden and maintain npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Etc/UTC"

    # **SECURITY HARDENING (for Version Updates)**
    # Wait 5 days before opening a PR for a new version. This gives time
    # for the community to discover and flag malicious packages.
    # This does NOT delay critical security patches for known vulnerabilities.
    cooldown:
      default-days: 5

    # **MANAGEABILITY**
    # Define separate groups for version updates and security updates.
    groups:
      # Group patch and minor version updates together to reduce PR noise.
      npm-version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      # Group all security updates into a single PR per run.
      npm-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"

    # **STABILITY (for Version Updates)**
    # Ignore major version updates, as they often contain breaking changes
    # and should be handled manually.
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

    # Use a clear, conventional commit message prefix. This applies to both update types.
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

    open-pull-requests-limit: 10

  # Harden and maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Etc/UTC"

    # Also apply a cooldown to GitHub Actions to avoid newly compromised actions.
    cooldown:
      default-days: 5

    # **MANAGEABILITY**
    # Group GitHub Actions updates into separate PRs for version vs. security.
    groups:
      # Group all version updates for actions together.
      actions-version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
      # Group all security updates for actions together.
      actions-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"

    # Use a clear, conventional commit message prefix.
    commit-message:
      prefix: "chore(ci)"
      include: "scope"

    open-pull-requests-limit: 5
