name: Publish Benchmark Summaries

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *' # daily at 06:00 UTC

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: '22'
      - name: Install deps
        run: npm ci
      - name: Run compare harness (single run)
        run: |
          node benchmarks/compare-lru-harness.mjs throughput-segmented-aggressive
      - name: Summarize last results
        run: |
          node benchmarks/summarize-profiles.mjs benchmarks 10
      - name: Upload summary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bench-summaries
          path: benchmarks/summary-*.json
