name: Deno CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deno:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps and build
        run: npm ci && npm run build
      - name: Deno tests
        run: deno task test
