name: Security-kit Hybrid CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # Phase 1: Node.js development workflow (existing)
  nodejs-development:
    name: "Node.js Development & Testing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build
      
  # Phase 1: Deno security validation (new)
  deno-security:
    name: "Deno Security Audit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run security audit
        run: deno task security:audit
      - name: Validate TypeScript
        run: deno check src/index.ts
      - name: Run Deno tests
        run: deno task test:deno
        
  # Phase 1: Supply chain security check
  supply-chain:
    name: "Supply Chain Security"
    runs-on: ubuntu-latest
    needs: [nodejs-development, deno-security]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: npm ci
      - name: Audit npm dependencies
        run: npm audit --audit-level moderate
      - name: Run comprehensive security scan
        run: deno task supply-chain:scan
        
  # Phase 1: Performance benchmarking
  performance:
    name: "Performance Benchmarks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - name: Run hybrid benchmarks
        run: npm run bench:compare